Fixes

diff --git a/flirt_mc b/flirt_mc
--- a/flirt_mc
+++ b/flirt_mc
@@ -25,8 +25,7 @@ cat << EOF
             -final      coregister mean image of motion corrected series
             -nIter      Number of iterations for coregistration (default: 1)
             -betpar     Parameter used for the bet call (default: "-r 30 -f 0.4")
-            -resample   resamples volumes to the size of the reference image
-            -rsmpl_hdr  resamples data to image size given by this header file (ignores -resample)
+            -rsmpl      resamples volumes to the size of the reference image
             -tmp        temporary directory where single 3D files are saved
             -keep       don't delete temporary files when finished
 
@@ -57,7 +56,6 @@ mask_thr=15
 outnm=${flnm}_mc
 dof=12
 rot_tol=6
-do_refmask=0
 do_inmask=0
 do_final=0
 tmpdir=`tmpnam tmpMC`
@@ -65,7 +63,7 @@ rm $tmpdir
 keep_tmp=0
 costfun="corratio"
 ref=0
-ip="trilinear"
+ip="spline"
 sincwd=5
 do_rsmpl=0
 sm_fwhm=0
@@ -85,11 +83,10 @@ do
         -dof)   dof=$2
                 shift 2
                 ;;
-        -ref)   ref=$2
+        -ref)   ref=$(remove_ext $2)
                 shift 2
                 ;;
     -refmask)   refmask=$2
-                do_refmask=1
                 shift 2
                 ;;
      -inmask)   inmask=$2
@@ -102,12 +99,8 @@ do
     -rot_tol)   searchtol="-searchrx -$2 $2 -searchry  -$2 $2 -searchrz  -$2 $2"
                 shift 2
                 ;;
-   -resample)   do_rsmpl=1
+      -rsmpl)   do_rsmpl=1
                 shift
-                ;;
-  -rsmpl_hdr)   rsmpl_hdr=$2
-                do_hdr=1
-                shift 2
                 ;;
          -ip)   ip=$2
                 shift 2
@@ -139,14 +132,6 @@ do
     esac
 done
 
-if [ $do_hdr -eq 1 ]
-then
-    if [ ! -e ${rsmpl_hdr}* ]
-    then
-        echo "ERROR: reference header $rsmpl_hdr does not exist!"
-        exit
-    fi
-fi
 
 #----------------------------------------------------------------------#
 # check whether directory allready exists
@@ -177,11 +162,14 @@ mkdir ${outnm}.mat
 #----------------------------------------------------------------------#
 # get the reference image
 reffl=${tmpdir}/ref
-refweight=${tmpdir}/refmask
-if [ -e "$ref" ]
+refweight=${tmpdir}/refweight
+if [ $(imtest $ref) -eq 1 ]
 then
+    echo "Using reference file: $ref"
     imcp $ref $reffl              # copy reference into temp directory
 else
+    echo "Using reference volume # $ref"
+
     fslroi $flnm $reffl $ref 1   # extract reference volume
     if [ $sm_fwhm != 0 ]
     then
@@ -191,23 +179,32 @@ else
 fi
 
 # weightning mask
-if [ $do_refmask -eq 1 ]
+if [ $(imtest $refmask) -eq 1 ]
 then
-    if [ -e "$refmask" ]
-    then
-         imcp $refmask $refweight
-    else
-        case $refmask in
-            thr)    fslmaths $reffl -thrp $mask_thr $refweight
-                    ;;
-            bet)    bet $reffl ${reffl}_bet -o -m $betpar -R
-                    immv ${reffl}_bet_mask $refweight
-                    ;;
-              *)    echo "ERROR: Unknown option <$refmask> for reference weightning"
-                    exit 1
-                    ;;
-        esac
-    fi
+        imcp $refmask $refweight
+        imcp $refmask ${tmpdir}/refmask
+elseif [ $(imtest ${reffl}_mask) -eq 1 ]
+        imcp ${reffl}_mask $refweight
+        imcp ${reffl}_mask ${tmpdir}/refmask
+else
+    case $refmask in
+        thr)    fslmaths $reffl -thrp $mask_thr $refweight
+                ;;
+        bet)    bet $reffl ${reffl}_bet -o -m $betpar -R
+                immv ${reffl}_bet_mask $refweight
+                ;;
+            *)    echo "ERROR: Unknown option <$refmask> for reference weightning"
+                exit 1
+                ;;
+    esac
+    imcp $refweight ${tmpdir}/refmask
+fi
+
+if [ $(imtest ${tmpdir}/refmask) -eq 1 ]
+then
+    do_refmask=1
+else
+    do_refmask=0
 fi
 
 #----------------------------------------------------------------------#
@@ -216,17 +213,13 @@ inweight=${tmpdir}/inmask
 flirt_fun_par=""
 
 flirt_fun_par="$flirt_fun_par -usesqform -cost $costfun -searchcost $costfun $searchtol"
-flirt_fun_par="$flirt_fun_par -dof $dof"
+flirt_fun_par="$flirt_fun_par -dof $dof -coarsesearch 30 -finesearch 6"
 
 if [ $do_refmask -eq 1 ]
 then
     flirt_fun_par="$flirt_fun_par -refweight $refweight"
 fi
 
-if [ $do_inmask -eq 1 ]
-then
-    flirt_fun_par="$flirt_fun_par -inweight $inweight"
-fi
 
 #----------------------------------------------------------------------#
 # prepare the arguments for the image transformation
@@ -237,6 +230,42 @@ if [ $ip == "sinc" ]
 then
     trans_fun_par="$trans_fun_par -sincwidth $sincwd -sincwindow hanning"
 fi
+
+#----------------------------------------------------------------------#
+# prepare volumes
+
+echo "preparing volumes"
+
+for curr_vol in $vol_lst
+do
+    init_par=""
+
+    cnt=$(($cnt+1))
+    echo -n "$cnt "
+
+    curr_vol=`remove_ext ${curr_vol}`
+    curr_vol=`basename ${curr_vol}`
+
+    if [ $sm_fwhm != 0 ]
+    then
+        fslmaths ${tmpdir}/${curr_vol} -s `sigma2fwhm $sm_fwhm`  ${tmpdir}/${curr_vol}
+    fi
+
+    # create a weighning mask for the current input
+    if [ $do_inmask -eq 1 ]
+    then
+        case $inmask in
+            thr)    fslmaths ${tmpdir}/${curr_vol} -thrp $mask_thr $inweight
+                    ;;
+            bet)    bet ${tmpdir}/${curr_vol} ${tmpdir}/${curr_vol}_bet -o -m $betpar -R
+                    ;;
+            *)      echo "ERROR: Unknown option <$inmask> for input weightning!"
+                    exit
+                    ;;
+        esac
+    fi
+done
+echo " - done"
 
 #----------------------------------------------------------------------#
 # run flirt on each volume
@@ -257,8 +286,6 @@ do
 
     for curr_vol in $vol_lst
     do
-        init_par=""
-
         cnt=$(($cnt+1))
         echo -n "$cnt "
 
@@ -267,98 +294,81 @@ do
 
         if [ $i -eq 1 ]
         then
-            if [ $sm_fwhm != 0 ]
-            then
-                fslmaths ${tmpdir}/${curr_vol} -s `sigma2fwhm $sm_fwhm`  ${tmpdir}/${curr_vol}
-            fi
-
-            # create a weighning mask for the current input
-            if [ $do_inmask -eq 1 ]
-            then
-                case $inmask in
-                    thr)    fslmaths ${tmpdir}/${curr_vol} -thrp $mask_thr $inweight
-                            ;;
-                    bet)    bet ${tmpdir}/${curr_vol} ${tmpdir}/${curr_vol}_bet -o -m $betpar -R
-                            immv ${tmpdir}/${curr_vol}_bet_mask $inweight
-                            ;;
-                    *)      echo "ERROR: Unknown option <$inmask> for input weightning!"
-                            exit
-                            ;;
-                esac
-            fi
+            init_par=""
         else
             preitr=$(($i-1))
             init_par="-init ${tmpdir}/${outnm}_itr${preitr}.mat/${curr_vol}"
         fi
 
-        flirt -in ${tmpdir}/${curr_vol} -ref $Fref -omat ${tmpdir}/${outnm}_itr${i}.mat/${curr_vol} $flirt_fun_par $init_par
-
-        if [ $do_hdr -eq 1 ]
+        if [ $do_inmask -eq 1 ]
         then
-            flirt -in ${tmpdir}/${curr_vol} -ref $rsmpl_hdr -o ${tmpdir}/mc_${curr_vol}_itr${i} -init ${tmpdir}/${outnm}_itr${i}.mat/${curr_vol} $flirt_fun_par -applyxfm
+            inmaskstr="-inweight ${tmpdir}/${curr_vol}_bet_mask"
         else
-            flirt -in ${tmpdir}/${curr_vol} -ref ${tmpdir}/${curr_vol} -o ${tmpdir}/mc_${curr_vol}_itr${i} -init ${tmpdir}/${outnm}_itr${i}.mat/${curr_vol} $flirt_fun_par -applyxfm
+            inmaskstr=""
+        fi
+
+        flirt -in ${tmpdir}/${curr_vol} -ref $Fref -omat ${tmpdir}/${outnm}_itr${i}.mat/${curr_vol} $flirt_fun_par $init_par $inmaskstr
+
+        if [ $do_rsmpl -eq 1 ]
+        then
+            flirt -in ${tmpdir}/${curr_vol} -ref $reffl -o ${tmpdir}/mc_${curr_vol}_itr${i} -init ${tmpdir}/${outnm}_itr${i}.mat/${curr_vol} -applyxfm $trans_fun_par
+        else
+            flirt -in ${tmpdir}/${curr_vol} -ref ${tmpdir}/${curr_vol} -o ${tmpdir}/mc_${curr_vol}_itr${i} -init ${tmpdir}/${outnm}_itr${i}.mat/${curr_vol} -applyxfm $trans_fun_par
         fi
 
         mc_lst="$mc_lst ${tmpdir}/mc_${curr_vol}_itr${i}"
         matlst="$matlst ${tmpdir}/${outnm}_itr${i}.mat/${curr_vol}"
     done
+    echo " - done"
 
-    if [ $i -lt $numiter ]
-    then
-        fslmerge -t ${tmpdir}/${outnm}_itr${i} $mc_lst
-        fslmaths    ${tmpdir}/${outnm}_itr${i} -Tmean ${tmpdir}/${outnm}_itr${i}_mean
+    fslmerge -t ${tmpdir}/${outnm}_itr${i} $mc_lst
+    fslmaths    ${tmpdir}/${outnm}_itr${i} -Tmean ${tmpdir}/${outnm}_itr${i}_mean
 
-        bet ${tmpdir}/${outnm}_itr${i}_mean ${tmpdir}/${outnm}_itr${i}_mean_bet -o -m $betpar -R
-        immv ${tmpdir}/${outnm}_itr${i}_mean_bet_mask $refweight
-        Fref=${tmpdir}/${outnm}_itr${i}_mean
-    else
-        fslmerge -t ${outnm} $mc_lst
-        mv ${tmpdir}/${outnm}_itr${i}.mat/* ${outnm}.mat/
-    fi
+    bet ${tmpdir}/${outnm}_itr${i}_mean ${tmpdir}/${outnm}_itr${i}_mean_bet -o -m $betpar -R
+    imcp ${tmpdir}/${outnm}_itr${i}_mean_bet_mask $refweight
+    Fref=${tmpdir}/${outnm}_itr${i}_mean
 done
 
 echo " - done"
 echo ""
 
-
-
-fslmerge -t ${outnm} $mc_lst
-
 #----------------------------------------------------------------------#
 if [ $do_final -eq 1 ]
 then
-    fslmaths ${outnm} -Tmean $tmpdir/final_mean
-    bet ${tmpdir}/final_mean ${tmpdir}/final_mean_bet -o -m -r 30 -f 0.4
-    CoM=`fslstats ${tmpdir}/final_mean_bet_mask -C`
-    bet ${tmpdir}/final_mean ${tmpdir}/final_mean_bet2 -o -m -r 30 -f 0.4 -c $CoM -R
+    echo "Perform a final co-registration to the reference image"
 
-    inweight=${tmpdir}/final_mean_bet_mask
+    flirt_fun_par="-dof $dof -usesqform -cost $costfun -searchcost $costfun"
+    flirt_fun_par="$flirt_fun_par -nosearch -coarsesearch 30 -finesearch 6"
+    if [ $do_refmask -eq 1 ]
+    then
+        flirt_fun_par="$flirt_fun_par -refweight ${tmpdir}/refmask"
+    fi
+    flirt_fun_par="$flirt_fun_par -inweight ${tmpdir}/${outnm}_itr${i}_mean_bet_mask"
 
-    flirt -in ${tmpdir}/final_mean -ref $reffl -omat $tmpdir/final_mean.mat $flirt_fun_par
+    flirt -in ${tmpdir}/${outnm}_itr${i}_mean -ref $reffl -omat $tmpdir/final_mean.mat $flirt_fun_par
 
     declare -a vols=($vol_lst)
     cnt=0
-    mc2_lst=""
+    mc_lst=""
     for curr_mat in $matlst
     do
         cvol=`basename ${vols[$cnt]}`
 
         echo "$cnt    $cvol    $curr_mat    mc2_$cvol"
-
         convert_xfm -omat $curr_mat -concat $curr_mat $tmpdir/final_mean.mat
 
-        flirt -in $tmpdir/$cvol -ref ${tmpdir}/final_mean -o $tmpdir/mc2_$cvol -init $curr_mat $flirt_fun_par -applyxfm
+        flirt -in $tmpdir/$cvol -ref ${tmpdir}/${outnm}_itr${i}_mean -o $tmpdir/mc2_$cvol -init $curr_mat  -applyxfm $trans_fun_par
 
         cnt=$(($cnt+1))
 
-        mc2_lst="$mc2_lst $tmpdir/mc2_$cvol"
+        mc_lst="$mc_lst $tmpdir/mc2_$cvol"
     done
-
-    fslmerge -t ${outnm} $mc2_lst
 fi
 
 #----------------------------------------------------------------------#
+fslmerge -t ${outnm} $mc_lst
+mv ${tmpdir}/${outnm}_itr${i}.mat/* ${outnm}.mat/
+
 fsl_mcpar $outnm.mat -corr -out ${outnm}.par
 
 #----------------------------------------------------------------------#
